### ISSUE TITLE
Problem with export

### ISSUE THREAD

**Issue by inodesrl** [Maatwebsite/Laravel-Nova-Excel#65] opened 2019-10-04 15:31 UTC
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [ ] Checked that your issue isn't already filed.
* [ ] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 
* Laravel version: 
* Nova version: 
* Package version: 

### Description

![Cattura](https://user-images.githubusercontent.com/21054404/66220514-7230dd80-e6cd-11e9-908a-c03ef6bc2608.JPG)

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:** 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by patrickbrouwers** [comment] 2019-12-24 10:22
Duplicate of #71

**Closed as completed by patrickbrouwers** 2019-12-24 10:22 UTC
