### ISSUE TITLE
Some columns don't show up when exported.

### ISSUE THREAD

**Issue by rickmacgillis** [Maatwebsite/Laravel-Nova-Excel#18] opened 2018-09-16 22:26 UTC
I spent the last few hours troubleshooting why some fields weren't showing up in my exports. After a while, I found out that `Laravel Nova Excel` makes the query into a model, at which point the `protected $hidden` property of the model stripped away the fields I was requesting with `only()`.

To avoid this issue, I suggest looping through the items in the `only()` list and setting those manually on the model. That will allow people to hide items in other places of in the code. (Ex. Sending models to JSON format as discussed in the official Laravel docs) It'll also allow people to export that which they'd like to export.

**Comment by patrickbrouwers** [comment] 2018-09-17 09:37
Fixed in the latest release. Should be more logical now.

**Closed as completed by patrickbrouwers** 2018-09-17 09:37 UTC

**Comment by rickmacgillis** [comment] 2018-09-17 18:15
@patrickbrouwers that release broke it worse. Now the headings no longer match up with the `only()` fields, and it no longer appears to listen to the directive at all. (I'm seeing data for columns not listed in the `only()` array.

**Comment by patrickbrouwers** [comment] 2018-09-17 18:44
Try to include a bit more information, especially (as specific as possible) code examples. I'm working with very little information here and "broke it worse", is not helping me understand your problem any better. I tagged a release which most likely will solve the issue with auto heading generation and only(). Your other problem I don't understand and cannot reproduce without a proper code example.

On a side node, it would be highly appreciated if you could be a bit more considered when replying to open source maintainers, we are also just human who are offering a free piece of software made and maintained in our free time. "broke it worse" is of course not very motivating to try and help you. Show some appreciation when someone tries to fix your problem.

**Comment by rickmacgillis** [comment] 2018-09-17 18:46
Wow. @patrickbrouwers your behavior is unacceptible. If you're having a bad day, that's on you, but don't take it out on people trying to help you improve your software. It'll get you nowhere with me, and I'll sooner move on.

**Comment by patrickbrouwers** [comment] 2018-09-17 19:04
If I had a bad day I wouldn't have replied to you in the first place. All your best efforts aside to try to improve my software, it doesn't take away that you can just be a bit more considerate when replying. A simple thank you goes a long way. That's all I'm asking for, just a little bit of respect.

**Comment by rickmacgillis** [comment] 2018-09-17 19:08
@patrickbrouwers If I didn't respect you, I wouldn't have contributed. While I appreciate your work, and even at times found that your work looks a bit like the way I write software, calling me inconsiderate because of something that was taken out of context is unacceptable.

For the record, "Broke it worse" is a subtle pun from the game "Dreamfall: Chapters" and even if you didn't get the pun, it's still nothing condescending.

**Comment by patrickbrouwers** [comment] 2018-09-17 19:12
So asking for a bit more appreciation is unacceptable... Could have just said thank you for my efforts, but you instead try putting it all on me. Very professional!

**Comment by rickmacgillis** [comment] 2018-09-17 19:13
@patrickbrouwers This ends now. I'm not going to fight with you. I said my piece.

**Comment by patrickbrouwers** [comment] 2018-09-17 19:14
I'm not aiming at a fight. But you clearly don't respect or appreciate me or my work enough to just give me a simple thank you. Who's having the bad day here?
